### ISSUE TITLE
Cannot install quickle via pip

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [jcrist/quickle#60]
Running `pip install quickle` fails with
```
ERROR: Could not find a version that satisfies the requirement quickle
ERROR: No matching distribution found for quickle
```
Not even if I put it into a requirements.in, running `pip-compile && pip-sync` from pip-tools fails with
```
Could not find a version that matches quickle (from -r requirements.in (line 68))
No versions found
Was https://pypi.org/simple reachable?
```
If I just remove quickle from requirements.in, everything works perfectly.

Environment: 
macOS 10.13.6 (17G65)
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)

**Comment by jcrist** [comment]
Quickly is python 3.8+ only, you're using python 3.7.

**Comment by BarnabasSzabolcs** [comment]
Good to know, thanks.
