### ISSUE TITLE
Support for dump() and load()

### ISSUE THREAD

**Issue by ddofborg** [jcrist/quickle#61]
I am missing `dump()` and `load()` functions for writing to and reading from file objects. This makes it easier to replace `pickle`. What is the reason those are missing?

**Comment by jcrist** [comment]
Apologies, this repo is no longer maintained (I'll archive it shortly). `quickle` was an interesting experiment, but for any use case where `quickle` might have made sense, `msgspec` (https://github.com/jcrist/msgspec) would likely be a better choice. `msgspec` supports all the types `quickle` does, while also being faster and using a standardized protocol (either JSON or MessagePack).

As for your specific question - the encoders/decoders (and in `msgspec`) don't work incrementally, but rather produce/consume an in-memory bytes object. As such, a `dump`/`load` method would be the following:

```python
def load(file):
    return loads(file.read())

def dump(obj, file):
    file.write(dumps(obj))
```

These methods could be added to `msgspec` (as mentioned above, this repo is archived), if `msgspec` suits your use case and you're still interested in this functionality, I'd encourage you to open an issue [here]( https://github.com/jcrist/msgspec/issues).
