### ISSUE TITLE
Can we add support for custom objects in the registry?

### ISSUE THREAD

**Issue by EdgyEdgemond** [jcrist/quickle#62]
uuid.UUID isn't supported etc, is there a way to tell it what to do with types it doesn't know how to handle? 

I know I can create customer encoder/decoders for json etc that can be taught how to handle new types.

**Comment by jcrist** [comment]
Apologies, this repo is no longer maintained (I'll archive it shortly). `quickle` was an interesting experiment, but for any use case where `quickle` might have made sense, `msgspec` (https://github.com/jcrist/msgspec) would likely be a better choice. `msgspec` supports all the types `quickle` does, while also being faster and using a standardized protocol (either JSON or MessagePack). In your case, `msgspec` already supports custom types, see https://jcristharif.com/msgspec/extending.html for more information.
