### ISSUE TITLE
Weak reference support?

### ISSUE THREAD

**Issue by markoh1** [jcrist/quickle#63]
Would it be possible to add weakref support to quickle.Struct? Thanks.
PS. I have tried to add __weakref__ to slots, but without success.

**Comment by jcrist** [comment]
Apologies, this repo is no longer maintained (I'll archive it shortly). `quickle` was an interesting experiment, but for any use case where `quickle` might have made sense, `msgspec` (https://github.com/jcrist/msgspec) would likely be a better choice. `msgspec` supports all the types `quickle` does, while also being faster and using a standardized protocol (either JSON or MessagePack). If `msgspec` would be sufficient for your use case, could you open an issue there about `weakref` support for `Struct` types? This is doable, but isn't currently supported.
